num1=int(input())
num2=int(input())
print(f"sum is {num1+num2},subtraction is {num1-num2}")
print(num1**num2)
print(num1+num2)
print(num1-num2)
print(num1*num2)
print(num1%num2)
print(num1/num2)
print(num1//num2)